strongdm/charts

deployments/sdm-client/Chart.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/Service.yaml, deployments/sdm-relay/values.yaml
- Often time we would want to add additional annotations in the service, for example to use AWS LB controller
=> [MAIN] Add annotation support for gateway/relay service

deployments/sdm-relay/templates/Deployment.yaml, deployments/sdm-relay/values.yaml
This PR adds the optional ability to specify additional labels and annotations on the Deployment of the relay. 
We use this to configure monitoring tools like Datadog
=> feat: Support custom labels/annotation on relay deployment

deployments/sdm-relay/templates/Deployment.yaml
The current structure applies the `serviceAccountName` to the container definition, but the reference documentation for the container definition doesn't seem to support a `serviceAccountName` field. Instead, it looks like this is supposed to be defined on the `spec` itself. This looks like it's causing my attempts to use this chart with a specific service account (rather than the `default` SA) to fail.
=> fix: apply service account to spec

deployments/sdm-client/Chart.yaml, deployments/sdm-client/templates/_helpers.tpl, deployments/sdm-client/values.yaml, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/values.yaml
at the request of a customer, make this date label optional. default it to true to not change existing installations.
feels a bit hacky adding a very bespoke value, but couldn't think of another way to do this if we don't want to rip the label out altogether. customers may be relying on it.
open to suggestions on naming and/or placement of the value.
=> make date label optional, but default to true for consistency

.pre-commit-config.yaml, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/README.md, deployments/sdm-proxy/templates/Deployment.yaml, deployments/sdm-proxy/templates/NOTES.txt, deployments/sdm-proxy/templates/Service.yaml, deployments/sdm-proxy/templates/ServiceAccount.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/templates/secret.yaml, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/README.md, deployments/sdm-relay/templates/ConfigMap.yaml, deployments/sdm-relay/templates/Deployment.yaml, deployments/sdm-relay/templates/ServiceAccount.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/values.yaml
Same thing as #27 but this time for the Proxy Cluster chart.
Also fixed a few things on the relay chart, namely around healthchecks and how we handle additional config. Specifically moving all the config options to values and setting them directly as env vars in `configmap.yaml`.
Removed the `envFrom` helper template because it's not being reused, we can define those in-line in `deployment.yaml` to require less context switching when determining how the app loads config.
=> Infra 921 proxy cluster refactor

.pre-commit-config.yaml, deployments/sdm-client/values.schema.json, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/Deployment.yaml, deployments/sdm-proxy/templates/post-install.yaml, deployments/sdm-proxy/templates/secret.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.test.yaml, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/Deployment.yaml, deployments/sdm-relay/templates/Secret.yaml, deployments/sdm-relay/templates/post-install.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.test.yaml, deployments/sdm-relay/values.yaml
- add `post-install` hook that creates a StrongDM Pod Identity Cluster resource.
- improve, simplify, and standardize how secrets are loaded into Pods.
- standardize the way we add annotations everywhere.
- beef up some of the pre-commit hooks with more test values, and introduce value schemas.
as an aside, there is lots of duplication between these two charts. i would love to introduce a pattern similar to what Bitnami does, wherein they publish a [common chart and include it as a dependency](https://github.com/bitnami/charts/blob/main/bitnami/postgresql/Chart.yaml#L17-L22) in their actual charts. shared code and helpers can go there and greatly simplify the other charts. a task for another PR.
i was able to validate the post install hook in our sandbox environment. status is unhealthy …
=> Chim 899 auto register pod identity cluster

README.md, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/NOTES.txt, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/templates/deployment.yaml, deployments/sdm-proxy/templates/post-install.yaml, deployments/sdm-proxy/templates/secret.yaml, deployments/sdm-proxy/templates/service.yaml, deployments/sdm-proxy/templates/serviceaccount.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/NOTES.txt, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/templates/deployment.yaml, deployments/sdm-relay/templates/post-install.yaml, deployments/sdm-relay/templates/pre-install.yaml, deployments/sdm-relay/templates/secret.yaml, deployments/sdm-relay/templates/service.yaml, deployments/sdm-relay/templates/serviceaccount.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
Addresses https://github.com/strongdm/charts/issues/8. Inspiration taken from the [Bitnami Helm charts](https://github.com/bitnami/charts/pull/30113).
Also removes the unused `maintenanceWindows` from `sdm-proxy`, and that value under `autoCreateNode` in `sdm-relay` next to the other values that configure that pre-install hook.
QA plan
---
With the following local setup:
```
~/scratch/helm: tree .
.
├── test-chart
│   ├── Chart.yaml
│   ├── templates
│   │   └── pod.yaml
│   └── values.yaml
└── values.yaml
```
Where `Chart.yaml` points to a local repo:
```yaml
apiVersion: v2
name: test
description: "Local Helm testing"
version: 0.1.0
dependencies:
- name: sdm-relay
version: 1.0.5
repository: file:///Users/kellen.anker/git/charts/deployments/sdm-relay
```
and the applied `values.yaml` is: …
=> allow overriding resource names and release namespace

.github/pull_request_template.md, CONTRIBUTING.md, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/README.md, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/templates/deployment.yaml, deployments/sdm-proxy/templates/post-install.yaml, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/README.md, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/templates/deployment.yaml, deployments/sdm-relay/templates/post-install.yaml, deployments/sdm-relay/values.yaml
- the default behavior for these containers is to automatically update themselves to the latest available version. as such, it's a bit misleading to pin to an `appVersion` after all. the field is optional in `Chart.yaml` so we're free to remove it. this sets a new default `strongdm.image.tag=latest`.
- users can still _implicitly_ version-pin by setting either `strongdm.image.digest` to any value or `strongdm.image.tag` to anything not "latest". `strongdm.config.disableAutoUpdate` is still available to explicitly pin to the current version.
- standardize on one way to use `default`.
- add a PR template.
=> pin to latest because nodes auto update by default

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
- The default log `storage=stdout` + `format=json` is _very_ noisy. This change defaults the chart to whatever the code defaults to, which feels reasonable.
- also name the values in a way that calls out they specifically configure the optional query logging, not the normal container logs.
- Also add support for debug logs.
- Was able to validate the changes in #38, cutting one more dev version to fully validate these logging updates.
- Make same values schema changes to `sdm-relay` chart.
I realize that changing values has user impacts, I hope for this to be the last such change for a little while. In an abundance of caution, though, I am calling for a minor version upgrade rather than a patch.
=> quieter default log config

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
When running multiple nodes in the same k8s cluster + namespace that are connecting to _different_ SDM control planes, services are not properly load balancing to just the Pods in their own Helm release. They're selecting all Pods across all such releases.
Add a new default selector label `app.kubernetes.io/instance: {{ .Release.Name }}` that will uniquely identify Pods in a namespace. You cannot have two Helm releases with the same name in a single namespace.
Also allow for additional selector labels. Didn't want to just throw all the global labels into this, it felt reasonable to create a new value to allow for higher granularity.
Finally, deprecate `SDM_DOMAIN` in favor of `SDM_APP_DOMAIN`,
=> allow additional selectorLabels for services

deployments/sdm-proxy/Chart.yaml, deployments/sdm-relay/Chart.yaml
selector labels are immutable, so this fix unfortunately introduces a breaking change. users will need to either 
- uninstall and re-install the chart
- manually delete the k8s deployment and run a `helm upgrade`
=> this is unfortunately a breaking change

.pre-commit-config.yaml, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl
address #43 and removes the duplicate `app.kubernetes.io/instance` labels
=> remove dupe labels

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.test.yaml, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.test.yaml, deployments/sdm-relay/values.yaml
Addresses #48, allowing for arbitrary key-value pairs to be supplied as environment variables. add a few different data types to `values.test.yaml`.
Considering this a `minor` version bump because it adds new functionality, but happy to discuss if folks disagree.
=> add support for additional, arbitrary env vars to be added to the ConfigMap

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/deployment.yaml, deployments/sdm-proxy/values.schema.json, deployments/sdm-proxy/values.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/deployment.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
Addresses #44, allows for proper scheduling rules to be applied to all Pods. Support multiple topology spread constraints as well.
=> allow Pod scheduling configs

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/deployment.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/deployment.yaml
Finalizes changes from #51 . fixes a typo from the previous commit.
=> fix typo, cut non-dev version

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/configmap.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/configmap.yaml, deployments/sdm-relay/templates/pre-install.yaml
addresses #47, we need some error checking around the returned value of `/sdm.linux admin node create`. this introduces a few things:
- check for a valid format of the generated `SDM_RELAY_TOKEN`
- add `set -e -o pipefail` for extra circuit breaking
- just to be safe, double-quote `$(cat /secrets/token)`
also update the `pre-install` Job's env vars to support `SDM_APP_DOMAIN`, which was updated in the ConfigMap in a previous change but missed here. moved this logic to a helper function so we don't make the same mistake again.
I accomplished the latter locally with 
```
~: helm install good-admin-token deployments/sdm-relay -f good.yaml
Thank you for installing sdm-relay....
~: cat good.yaml
strongdm:
config:
appDomain: app.snd.strongdm.com
auth:
adminToken: REDACTED_BUT_VALID …
```
=> Better error handling

deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
these values are unused, and were actually a lingering copy-paste typo from the large refactor. will install into a k8s cluster and follow up with a PR to bump to `2.3.3`.
=> remove a few svc/pod port values

.pre-commit-config.yaml, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/pre-install.yaml, deployments/sdm-relay/values.schema.json, deployments/sdm-relay/values.yaml
as well as the bitnami/kubectl image
addresses #57. fixes logic to properly allow overriding the public ECR image registry. also adds the ability to override the `bitnami/kubectl` image used during the relay pre-install hook.
=> actually allow overridding our image repo

.pre-commit-config.yaml, deployments/sdm-client/Chart.yaml, deployments/sdm-client/templates/configmap.yaml, deployments/sdm-client/values.schema.json, deployments/sdm-client/values.yaml
allow clients to also auto update, feasible now after the previous change to the readiness check
=> Allow client updates

deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/clusterrole.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/clusterrole.yaml
also omit `spec.metadata.namespace` on these resources as they're non-namespaced and the field is ignored.
there is some precedence here; for example, the AWS LB controller does this to allow for multiple installations in the same cluster.
=> ensure unique cluster-scoped names so we can reuse release names

.pre-commit-config.yaml, deployments/sdm-client/Chart.yaml, deployments/sdm-client/templates/_helpers.tpl, deployments/sdm-client/templates/configmap.yaml, deployments/sdm-client/templates/deployment.yaml
disable auto updates for clients until we can dedicate more time to ensuring they don't just crash loop immediately
=> disable client auto updates again

.pre-commit-config.yaml, deployments/sdm-proxy/Chart.yaml, deployments/sdm-proxy/templates/_helpers.tpl, deployments/sdm-proxy/templates/post-install.yaml, deployments/sdm-proxy/values.test.yaml, deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/_helpers.tpl, deployments/sdm-relay/templates/post-install.yaml, deployments/sdm-relay/values.test.yaml
on some combinations of inputs, the post-install SDM CLI command was invalid, specifically including extra whitespace like:
```bash
/sdm.linux admin clusters add k8spodidentity \
--certificate-authority /var/run/secrets/kubernetes.io/serviceaccount/ca.crt \
--healthcheck-namespace default \
\
\
release-name-cluster-zLZnY
```
this change removes the extra whitespace and cleans up the command a bit by also moving the extra args into the helper function.
=> fix newlines when templating post-install SDM CLI command

deployments/sdm-relay/Chart.yaml, deployments/sdm-relay/templates/pre-install.yaml
Corrected templating to correctly specify a default bitnami image for sdm-relay
Before change:
```
[HW-0368:sdm-relay] on 83-bug-default-image-does-not-template-correctly!
[anthony.volkov]% helm template test-relay . --set strongdm.autoCreateNode.enabled=true --set strongdm.auth.adminToken=dummy-token | grep -i bit
image: bitnami/kubectl:%!s(uint64=1).%!s(uint64=31)
```
After change:
```
[HW-0368:sdm-relay] on 83-bug-default-image-does-not-template-correctly!
[anthony.volkov]% helm template test-relay . --set strongdm.autoCreateNode.enabled=true --set strongdm.auth.adminToken=dummy-token | grep -i bit
image: bitnami/kubectl:1.31
```
=> 83 bug default image does not template correctly
